intsall.packages("sqldf")
library("sqldf")
stu<-read.csv(file.choose())
stu
View(sqldf("select * from stu"))
sqldf("select count (*) from stu")
sqldf("select * from stu where marks>80")
sqldf("select *from stu where marks<80")
sqldf("select * from stu where name='Veer'")
sqldf("select * from stu where marks==45")
sqldf("select name from stu where marks==45")
sqldf("select distinct name from stu")
min(stu$marks)
max(stu$marks)
sum(stu$marks)
nrow(stu)
ncol(stu)
nrow(stu[stu$marks==33,])
nrow(stu[stu$marks>33,])
sqldf("select * from stu limit 3")
sqldf("select * from stu order by name desc limit 4") 
sqldf("select name,marks from stu order by name,marks desc limit 3")
sqldf("select name,roll_no,marks from stu order by name desc,marks  limit 20")
sqldf("select * from stu order by name desc")
sqldf("select * from stu where name like '%s'")
sqldf("select * from stu where name like 'V%'")
sqldf("select * from stu where name like '%k%'")
sqldf("select name as N, marks as M from stu")
sqldf("select sum(marks)from stu")
sqldf("select avg(marks)from stu")
#group by************************************************
sqldf("Select sum(marks) from stu ")
sqldf("Select sum(marks) from stu where name in ('Vikas','Ankit') group by name")
sqldf("Select name,sum(marks) from stu group by name")
sqldf("select roll_no,name from stu group by name having sum(marks)>0")
sqldf("select marks,name from stu group by name ")
sqldf("select roll_no,marks,name from stu group by name ")
sqldf("select name,marks,roll_no as reg_no from stu group by name ")
#___________________________________
a=sqldf("select name from stu ")
head(a)
b=sqldf("select marks from stu order by name")
head(b)
b=sqldf("select marks from stu order by name")
head(b)

